version: '3'

services:
  postgres_db:
    restart: always
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dblocks
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
